### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by JOHLC**
What do the panic switches do? 
If I have paid monitoring, does activating the police or fire switches contact those agencies?

### CODE REVIEW

**Review by JOHLC — COMMENTED** [review]
Would need to fill in the blanks here with a description for each

**Comment by tsightler** [comment]
To me this seems self-explanatory.  They function identically to the sliders in the Ring App, they literally do exactly the same thing, I'm not looking to reproduce the Ring user guide.  It may be reasonable to add some additional description to the section around enabling these switches, but adding that in supported features section seems like not the correct place.

**Comment by JOHLC** [comment]
I don't currently have paid monitoring so I have never seen that and was confused 

I added:
      - Panic Buttons (note: Paid professional monitoring is required):
        - Police - summons the police
        - Fire - summons the fire department

**Comment by tsightler** [comment]
The panic switches can still be useful even without paid monitoring, but only for monitoring the alarm state.  The "police" panic shows it "On" state any time the alarm is triggered in any "burglar" state, and the "fire" panic shows it "On" any time the alarm is triggered in any "fire" or "co" state.  Without paid monitoring it obviously can't contact police/fire services.  Otherwise you'd have to monitor for each alarm state individually to know if a triggered alarm is burglar vs fire (there are at least 7 such states).

**Pull request closed without merging**
