### PR TITLE
Attempt for Ring modes support

### PR DESCRIPTION
**Pull request by denniswham**
This is an attempt to include support for the Ring Modes. I'm by no means a dev, so to be honest no clue if I come anywhere near ;-)

I took your comment as a starter and created  a modes-panel (based on the security panel), created a modes-device (based on the security-device), and changed the util and ring-mqtt.

Could you please have a look whenever you have time -no rush of course!
Happy to hear the feedback if it all makes sense

### CODE REVIEW

**Comment by tsightler** [comment]
Nice.  Don't worry about not being a dev, I'm certainly not one either so we can both not be devs together. 

Quick glance looks pretty good.  One initial thought is that I don't know if it needs an entire "modes-device.js" file as it looks like the only difference is modeTopic vs alarmTopic.  Maybe it would be best to just rename existing "alarm-device" to something like "base-device" and use a conditional to set the correct property.  Or maybe there's a better way than that even.  I'll try to dig through it in a little more detail tonight.

**Comment by tsightler** [comment]
Has this code been functionally tested at all?  Looking at it I can't see how it could work.

For example, for the component type, it's set to "modes_control_panel" but this is for defining the HA component class, and, from the perspective of HA, this will still be an alarm control panel so the class should not change.  Otherwise, HA won't know what to do with it.

Also, for setting modes it appears to be calling the alarm functions "location.disarm()/armHome()/armAway()", but modes uses a different function, setLocationMode('away/disarmed/home').

**Comment by denniswham** [comment]
Thanks a lot, will take a look a bit later in the week, if there is anything left to do. I understand your line of thought.

And happy to be fellow non-devs ;-)

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by tsightler** [comment]
Looking through this a little more, I don't really understand the adding of mode devices.  Modes are nothing more than another toggle that sets camera to disarm/away/stay just like the alarm panel.  All that is needed is the modes-panel and a few tweaks to ring-mqtt.js to detect if a given location has modes enabled or not and, if so, create another alarm control panel for setting the mode.  Would probably also need a config option to toggle it on/off since it requires another polling session which must be explicitly enabled in the API.

I may take the modes-device.js file as a start, and rename it to modes-panel.js and then see if I can make the required tweaks and integrate it.

**Comment by tsightler** [comment]
I've decided to close this pull request because I don't believe the code here is functional, however, your contribution inspired me to create a [new branch](https://github.com/tsightler/ring-mqtt/tree/modes) for modes support and put some work into modifying your modes-panel.js to be functional.

I think I've managed to get this to a state where it could work, but I still need to integrate the mode panel device into ring-mqtt.js.  Since the nodes panel is not a "real" device returned by the Ring API, and I never really built the code to deal with the scenario, I'll have to create some way to inject a virtual device.  I think I've come up with a super easy way to to this, basically just detect if a location has modes enabled and, if so, build a simple virtual device and add it directly to the returned devices array before calling the publish function.  Unfortunately, I ran out of time to implement that tonight.

If I can sneak an hour or two tomorrow evening I'll try to finish that up and see if I can test it.  I'll post details in the issues topic here: https://github.com/tsightler/ring-mqtt/issues/64.

Thanks again for the contribution.

**Pull request closed without merging**
