### PR TITLE
Add support for 3rd party z-wave lights and switches

### PR DESCRIPTION
**Pull request by bryanhatwood**
I've updated ring-alarm-mqtt.js to support third-party z-wave lights and switches that have been added to the Ring Alarm system. This partially addresses issue #16 

I've attached a screen shot showing the switch and light controls that appear in Home Assistant after the API was updated and found the devices on my Ring system
Screen Shot 2019-10-21 at 4 04 32 PM

### CODE REVIEW

**Comment by bryanhatwood** [comment]
btw I'm new to HA, Typescript, MQTT, etc. so I apologize for the messy commits! Recommend squashing into single commit once we fix any issues with it.

**Comment by sktaylortrash** [comment]
@bryanhatwood are your changes still working for you? I have replaced the original script with yours but do not see any MQTT topics for the 3rd party switch I have on my system

**Comment by bryanhatwood** [comment]
@sktaylortrash Yes still works for me. I have the script set up through a [custom Hassio add-on](https://github.com/bryanhatwood/ring-alarm-hassio-addon). I just modified the add-on to point to my forked repo so that it grabs the script with my changes to support switches and lights.

If you use the add-on, you can view the logs and you should see your switches in the log lines as such:
2020-01-17T17:36:12.123Z ring-alarm-mqtt ring/{{uuid}}/alarm/light/{uuid}}/state OFF
2020-01-17T17:36:12.123Z ring-alarm-mqtt ring{{uuid}}/alarm/light/{{uuid}}/attributes {"tamper_status":"ok"}

or:
2020-01-17T17:36:12.125Z ring-alarm-mqtt ring/{{uuid}}/alarm/switch/{{uuid}}/state OFF
2020-01-17T17:36:12.126Z ring-alarm-mqtt ring/{{uuid}}/alarm/switch/{{uuid}}/attributes {"tamper_status":"ok"}

How do you have the script set up in Home Assistant? I can try to help debug.

**Comment by sktaylortrash** [comment]
Thanks for the reply. 
I don't actually use HA all my interactions are through node-red so I was monitoring my broker on script startup and when I triggered my switch from the ring app to find the topics as I had done with the sensors and locks and wasn't seeing anything. I have an HA instance I can startup if that's needed for this case

**Comment by bryanhatwood** [comment]
I see. In that case, you might try using the Ring API directly just to make sure your switches are showing up: https://github.com/dgreif/ring

That's what I used to debug and make my changes. By default, 3rd party zwave switches will show up as a "light". But my script makes it so if you change the category of the device in the Ring app to "outlet" it will show up as a "switch" in HA.

Beyond that, I would suggest the debug commands in the README to see what's going on:
DEBUG=ring-alarm-mqtt ./ring-alarm-mqtt.js

**Comment by sktaylortrash** [comment]
Thanks for giving me somewhere to look I appreciate it

**Comment by WisChrendel** [comment]
Does this work with dimmers? I purchased an Innovelli dimmer just to play around with it thinking I could connect it to the z wave hub. I didn't consider the fact that I am connected to that hub with this program. I assume Ill need to get a z wave stick

**Comment by tsightler** [comment]
Probably not as a dimmable light is technically a different device class.  Assuming Ring supports them then it might be possible to support them in the script, but there's certainly no support now and I don't have access to any such devices at this time so someone would have to act as a proxy to provide the device information from the Ring API.

Otherwise, yes, adding a zwave stick to get direct connectivity might be preferred.

**Comment by WisChrendel** [comment]
Ya I was digging through the api requests through the online portal and couldn't find where it lists all the devices/info. Really new to all this but figured that would a good place to start to see the device type ring puts it under.  Found all my cameras and the alarm hub but can't find the other devices under it. Where would I look to find them?

**Comment by tsightler** [comment]
If you use the [ring-client-api](https://www.npmjs.com/package/ring-client-api) then you can just use the getDevices() function to get all devices.  Does Ring even support the dimmable switch?  I know they support some generic sensors and switches/lights, but I wasn't sure how extensive that support was.

**Comment by WisChrendel** [comment]
Ya, they do. I actually figured the ring app would just treat it as a switch. However, inside the app there is a slider where you can adjust the dimmer

**Comment by tsightler** [comment]
In that case it's almost certain they should be visible in the devices API.  I'd just need a dump of the device properties to figure out what to add.  I'd guess it wouldn't be too bad, although I can image one issue is that, right now, everything supports only a single command topic, while, for a dimmer, it would likely need two, one for on/off and one for dimmer value.

If you look in the ring-alarm-mqtt repo there is a second script called ring-dump-devices.js that I added recently that just crudely dumps the devices output to a file, but that's really all that's needed to understand a device and add it.  I'm certainly open to supporting them if you can provide the required information.

**Comment by WisChrendel** [comment]
Sure, I don't mind at all! Here is the specific info about the switch, if you need my full device dumb, let me know

```
{
  "data": {
    "adapterType": "zwave",
    "adapterZid": "2fe3421e-94dc-41dd-ab08-f518577d0b0f",
    "batteryStatus": "none",
    "categoryId": 2,
    "commStatus": "ok",
    "commandTypes": {
      "communication-poll": {
        "requiresTrust": false
      },
      "reconfigure.start": {
        "requiresTrust": false
      },
      "update-node-neighbors.start": {
        "requiresTrust": false
      }
    },
    "deviceFoundTime": 1580605119332,
    "deviceType": "switch.multilevel",
    "fingerprint": "798.1.1",
    "lastCommTime": 1580610658722,
    "lastUpdate": 1580610663092,
    "managerId": "zwave",
    "name": "Multilevel Switch 12924",
    "pollInterval": 0,
    "roomId": 1,
    "setupByPluginStatus": "complete",
    "setupByUserStatus": "complete",
    "subCategoryId": 0,
    "tags": [],
    "tamperStatus": "ok",
    "zid": "a7a093e4-4e6b-4cfc-a82b-86d089c8f980",
    "level": 1,
    "on": false
  }
```

**Comment by WisChrendel** [comment]
On better thought, I am not sure if there is an any issue with sharing that data publicly. I assume not, but just want to be sure before I just drop it in the public eye. What is the best way to share it with you?

**Comment by tsightler** [comment]
Probably no issue, but I understand being concerned about it, you can email me directly using my github username at gmail.  I received your email notification previously and it looks pretty simple to at least add support for on/off.  It's not clear to me how to set the level or what the values are.  In the example you sent the level was 1, is that "off" I guess?  I'd need to at least know the range (the values for min/max brightness and I'll have to see if I can figure out the command to set the level as that is non-obvious.

**Comment by tsightler** [comment]
OK, nevermind, I see how to set the level now:

setInfo({ 
    device: { v1: { level: level / 100 } }
})

I'll try to look at this tomorrow, but, because I this will need a few more changes and I don't know how MQTT and HA handle this, it may take a little more time, but I appreciate the info.

**Comment by WisChrendel** [comment]
No problem, ya if you need me to send anything else I can do so. Let me know if I need to set any device states and pull a log file for it. 
Not worried about timing, I am just starting to learn everything Hass, so I will probably tinkering a ton over the next few weeks. Plenty of time. I appreciate the help

**Comment by sktaylortrash** [comment]
@tsightler thanks for the dump script. It shows why my 3rd party switch wasn't working as well as it is also devicetype switch.multilevel. 
For brightness in HA you need two more topics and one configuration variable
brightness_command_topic
brightness_state_topic
brightness_scale  (ie 100 if it's 1-100)

**Comment by tsightler** [comment]
If anyone can share with me what the Ring API shows as the level value when a device is at maximum brightness that would be very useful.  It appears looking at the Homebridge example that the scale in Ring is only 1-10.

**Comment by WisChrendel** [comment]
It looks like it between 0 and 1 and it holds its previous state when its off and on. So I can set it at 50% and then turn it off and when I turn it back on, in app, it goes back to 50%
 
level: 0
level: 0.5
level: 1

**Comment by tsightler** [comment]
Thanks! That makes sense not that I'm looking at the Homebridge code again I see that Homebridge natively uses 0-100 and then in the code for Ring it's doing multiply/devide by 100 when reading/writing via Ring API.

I've got most of this coded up now, just a few things to work through and I'll publish something that somebody can test.

**Comment by tsightler** [comment]
I pushed an update today that attempts to add support for "switch.multilevel" class devices.  It took more changes that I had hoped so, with the fact that I don't have such a device to test, I'm pretty concerned that I may have broken something or that it just won't work at all, but if someone has a dimmer connected to their Ring alarm I'd love to test it.

**Comment by WisChrendel** [comment]
Just tested. The multilevel switch does not show up, everything else still works fine though.

**Comment by tsightler** [comment]
Shoot...transposed the letter in the world "switch" in the discovery routine (had "swtich" instead), exactly the kind of thing I always worry about when I don't have a way to test.  Took another glance through the code and don't see anything else obviously wrong so hopefully you don't mind trying again.

**Comment by WisChrendel** [comment]
I even check the code myself to make sure there wasn't anything like that and didn't notice it haha. Checking now

**Comment by WisChrendel** [comment]
Ok so it discovers the light and recognizes states when the light is controlled manually and shows up great in homekit. However, something about the sending commands back to the switch does not work. Going to try to run debug right now

**Comment by WisChrendel** [comment]
Sending a Debug file to your email. Looks like it might have broken the sending method for all devices. I receive status updates but cannot send any.

**Comment by tsightler** [comment]
Yeah, that's definitely the part that I was most concerned about as I completely rewrote the "setSwitchState" function.  That being said, it actually looks like it's failing before it gets there are there are not lines in the debug log from that function.  It's obviously some type mismatch, but, because I didn't get any real debug messages I'm not sure where it's coming from.

So, just to be clear, you see light state and dimming state properly reflected in HA if you change the dimming manually or via Ring app?  It's only when you attempt to use HA to change the device (either on/off or change brightness) that you get the error and the error message causes the script to crash out?

**Comment by WisChrendel** [comment]
It recognizes off and on, It does not recognize level. Additionally, it seems to crash during an initialization step before I do anything. However, it still receives state changes after crashing, maybe because its already subscribed to the MQTT topics? (I don't completely understand how that works.) So I wonder if there is just an initialization step with the brightness level that is causing it to fail right now.

**Comment by tsightler** [comment]
OK, apparently I was overly optimistic of my ability to code this.  It didn't look very difficult but, after reading some of the MQTT HA threads, perhaps it's more complex.  Maybe I'll have to break down an buy a Zwave dimmer or at least attempt to figure out a way to emulate one on the HA side.

**Comment by WisChrendel** [comment]
No problem. I probably just need to break down and buy a z wave hub. I was just trying to be cheap and wanted to be able to control my office light automatically throughout the day. It makes sense for me to get a z wave hub though

**Comment by tsightler** [comment]
Well, it certainly should be possible to use via Ring.  I don't have and dimmers in my setup but it seems that lovelace doesn't automatically add brightness sliders for dimmable lights, you have to click the entity to see this option.  I don't see any reason why this part wouldn't be working as I can see the brightness command and state topics being sent and the values being sent on the state topic but there certainly my be some subtlety that I'm missing.

I'll try to think through it again tonight, maybe I can at least figure out where the current error is coming from since it happens before you try to do anything.

**Comment by WisChrendel** [comment]
Ya if you can figure out where `The "string" argument must be of type string or an instance of Buffer or ArrayBuffer. Received type number (100)` is coming from, everything else looked good in the code to me. However, I am probably not the best person to review the code as I am still pretty new to all of this

**Comment by hfcheng66** [comment]
thanks for the great repo! quick question, what kind of z-wave devices can be added to ring alarm base station?

**Comment by tsightler** [comment]
@WisChrendel  After thinking about the fact that the error happens before you even attempt to do anything, I believe that the only place this error could come from is the attempt to publish the brightness state.  That value is a number, which I have to do some math on, and I was passing it directly to publishMqtt, which only accepts string and buffers (exactly as the error stated).  I've now added an explict toString() conversion for the brightness value before attempting to publish via MQTT.  I'm hopeful that might be enough to at least get past that message as that part of the code really didn't change much, only a few lines.

**Comment by WisChrendel** [comment]
Nice, its now getting past that without error. Here is the new error haha!

```
(node:28885) UnhandledPromiseRejectionWarning: SyntaxError: Illegal break statement
    at processCommand (/opt/ring-alarm-mqtt/ring-alarm-mqtt.js:499:17)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:28885) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:28885) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by tsightler** [comment]
OK, good, at least that's where I thought the errors might be since that routine was mostly re-written.  I'm pretty sure that error is because I pulled the if (!device) outside of the case statement and thus you can't have a break command there.  I've fixed that.  Sorry for driving you nuts, I should have caught that one for sure.

**Comment by sktaylortrash** [comment]
Didn't get to test the intervening ones. But this last update seems to be working for me. Commands to adjust brightness and on/off for the variable level switch are working

**Comment by WisChrendel** [comment]
All good! I own my own business and the lightswitch is about 8 ft from me. So it takes me 3 minutes to test. Everything is working! Thanks for getting this updated so fast. Now to install my 3 additional ones

**Comment by tsightler** [comment]
Great news!  I guess I shouldn't be too disappointed as I guess that mostly just hacks at this stuff it turned out the errors were all just silly goofs, a typo, a simple type mistmatch, and forgetting to remove the break when I moved that line outside of the case statement.  Nothing was wrong with the actual logic of the code apparently, just little syntax things.  I'm sure if I did this on a daily basis I'd get way better at it!

Seriously, thanks for all the help, no way I'd be able to do that without the information you provided and a lot of people just don't understand why every device doesn't just automatically work, not realizing that every device category needs specific code to make it work.

Now I need to start the refactor of this thing, it's really grown way beyond the original vision and is becoming a little bit of a nightmare to support where little changes to add support for one thing tend to break other things.  I need to merge the camera support in and all of the fixes I have in that tree but putting all of that in one monolith seems like a bad idea.  That'll be my project for the next couple of months.

**Comment by WisChrendel** [comment]
Well I really appreciate it. Ring integration makes home assistant 110% worth it for me. Ring does such a great job of making an affordable plug and play system having this integration is perfect. All they need now is a glass break sensor.....

Tag me if you ever need me to test anything I’m home 7 days a week haha

**Comment by sktaylortrash** [comment]
@tsightler thanks for all your work on making the dimmers available. Above and beyond for a hobby project

I realized after the fact that my z-wave fan was showing as a light in HA. So I hacked up a fork of today's work that recognizes if a switch is set to fan (category-id 17 rather than 2). If a device is set as a fan it sends fan specific MQTT setup instead of a light to HA. 

It does work and regular dimmers still send appropriate data. But I could not figure out how to filter the brightness topic out vs the speed. So on a speed state change it still sends the brightness.  Even though everything ignores it. So clearly not a complete solution and not something I'd submit for merge.  But if anyone has a Z-wave fan controller and wants it to show as one in HA that version is in my repo - [https://github.com/sktaylortrash/ring-alarm-mqtt](https://github.com/sktaylortrash/ring-alarm-mqtt)

**Comment by tsightler** [comment]
@sktaylortrash Thanks for this.  I think we could clean it up and make it mergeable.

Regarding brightness vs speed, I had seriously considered using a single topic, something like "level", that would be more generic since I anticipated there could be things other than brightness.  So we would have "level_command" and "level_state" and it would be the same for both lights and fans but just have different values.

Then we'd just have to pass the component type to setSwitchState and make the decision on whether to send the value of 0-100 or "low/medium/high" based on that.  Might even shift that to a function so it wouldn't be so ugly in the code, or I guess could make a separate "setFanState" function instead, might be easier/cleaner.

Now that I think about it, perhaps merging the dimming capability into setSwtichState was a mistake that complicated things.  I could easily have setSwitchSate, setDimmerState, and setFanState, with the latter two calling setSwitchState for the on/off function.

That being said, it's exactly this reason that the code needs to be refactored, then we just put the logic in separate files for each device type and get rid of all the complex nesting.  I'll work on that project over the next few months so that I can merge the camera support.  I just never wrote the original project expecting there would be so many devices.

**Comment by tsightler** [comment]
Just FYI, as I was working on the refactor which is now published, I used your code as a base a included fan support.  There were some weird quirks with the UI of the fan component because, if you have two outstanding changes, like setting a level and state, which happens when, for example, the switch is off and you select "high", the HA UI reverts all other values to their prior states, which is confusing at best, and sometimes leads to the device ending with the original level instead of the old level.

After what seems like forever experimenting I think I've worked out how to handle that little issue and it seems pretty solid now.  If anybody happens to have Zwave fans or multilevel switches and wants to let me know how it works for them I'd love to hear about it.

**Comment by sktaylortrash** [comment]
I'll try and get the update installed tonight and let you know how the fan stuff turns out

**Comment by sktaylortrash** [comment]
@tsightler switched over to the latest code in the repository. No issues at first glance. The new fan entity from your version of the script took over for mine without creating a new device. As a result, I've deprecated that fork. 

Also just a note but if you're looking for others to check out multi-level function for you. It might behoove you to post it outside this merged commit or they'll probably never see it.

BTW great work on the refactor much easier to follow and expand as needed now.

**Comment by tsightler** [comment]
Thanks @sktaylortrash.  I mainly just posted here because I had used your code as the initial base for the work to include support.  I've tested about 3-4 different dimmers in switch and fan mode so I thought it would be fine, but just wanted to be sure.  I think everything in the new code is working pretty well at this point, the fan was the last component.  Thanks for the testing!

**Pull request merged**
